### PR TITLE
Random generator static variable was added.

### PR DESCRIPTION
**Pull request by SoftIntellectTDB**
There was continues creation of a Random object in one of the files. It is RAM and CPU consuming. Also it is not proper pseudo random number generator usage.

### CODE REVIEW

**Comment by SoftIntellectTDB** [comment]
It is a small fix and it is not so important. I will offer something more general.

**Comment by SoftIntellectTDB** [comment]
I have added only a single instance for pseudo-random number generator.

**Comment by chesterbr** [comment]
Hi! Thanks for the fix. I'm just thinking whether it is worth (complexity-wise) introducing a new class (without a clear role) just to hold the a global random number generation.

Looking around a bit (I've been away from Java) it seems `Math`already provides this functionality in the form of a static [utility method that keeps a shared `Random` internally](http://docs.oracle.com/javase/6/docs/api/java/lang/Math.html#random%28%29). Could you consider using that instead of introducing a new class? Thank you.

**Comment by SoftIntellectTDB** [comment]
It is up to you. You are the owner of the project and you should rule how the classes are organized.

It is a common practice to have Util or Common class in which we put all common global constants or common static methods. If the project is bigger there is even util package (for example java.util in J2SE).

In my personal opinion it is a better design, smaller code and easier to read program. It is better organization a single name as Util.PRNG is used everywhere. Before that it was random or rand. In some places it was private in other places it was protected. 

I will not suggest you to use Math.random(). This method has statistical problems, because the numbers form this method have weak statistical properties. Also the numbers generated are between 0.0 and 1.0 which is not very proper in your case.

**Comment by chesterbr** [comment]
@SoftIntellectTDB thank you once again for the contribution and from the point of view. I agree `Math.random()` may not have the best statistical properties (although I'd find it hard to be a problem for this particular use case), but I'd rather not introduce a utility class (there are [several](http://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html)  [discussions](https://stackoverflow.com/questions/3340032/utility-classes-are-evil) about them, but I'd rather avoid if I can).

Could you please revert the last commit so I can merge this PR? Thank you!

**Comment by SoftIntellectTDB** [comment]
@chesterbr No problem. I did revert the last commit. Is everything fine now?

**Comment by chesterbr** [comment]
👍 , thank you! 😄

**Comment by SoftIntellectTDB** [comment]
:+1:

**Pull request merged**
